Let's begin with an introduction to pytorch.

In [35]:
import numpy as np 
import torch


The principal element in pytorch is the tensor.

In [36]:
#that is a list.
data = [
    [1, 2],
    [3, 4],
    [5, 6]
]
print(data)
print(type(data))

#that is a tensor. quando lavoreremo con le immagini lavoreremo con tensori a 4 dimensioni
#Questo perchè l'immagine sarà formata da 3 dimensioni: altezza, larghezza e canali (RGB) più una batch dimensione. lo vedremo in seguito...
x_data = torch.tensor(data) 
print(x_data)
print(type(x_data))



[[1, 2], [3, 4], [5, 6]]
<class 'list'>
tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>


In [37]:
#Posso creare un tensore partendo da un array numpy.
import numpy as np
np_array = np.array(data)
print(np_array)
print(type(np_array))

#and then
#prende in oggetto un numpy array e lo trasforma in un tensore torch.
x_tensor = torch.from_numpy(np_array)
print(x_tensor)
print(type(x_tensor))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>


In [38]:
#alcune funzioni:
x_ones = torch.ones(size=(4,4,3) , dtype=torch.int32) #this is a 4x4 x3 tensor. 
print(x_ones)
print(x_ones.shape)
print(x_ones.dtype)


tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)
torch.Size([4, 4, 3])
torch.int32


In [39]:
x_zero = torch.zeros(4, 4, 3)
print(x_zero)
print(x_zero.shape)
print(x_zero.dtype)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([4, 4, 3])
torch.float32


In [40]:
x_rand = torch.randn(size=(4,4,3) , dtype=torch.float32) #questa la posso proprio immaginare come un'immagine.
print(x_rand)   
print(x_rand.dtype)
print(x_rand.shape)

tensor([[[ 0.5016,  0.5247, -0.2674],
         [-0.4590, -0.1240, -2.5421],
         [-0.1483,  0.1569, -1.3072],
         [-0.0274,  0.0912,  0.6977]],

        [[ 1.7896,  0.6472, -1.4049],
         [-0.8284, -1.1559, -0.2797],
         [-0.0488, -2.4528, -0.4027],
         [ 0.4906,  0.5318,  1.8865]],

        [[ 1.8007,  0.4951,  0.2820],
         [ 1.0385, -0.6607, -2.4513],
         [ 0.1685,  1.3418,  0.7777],
         [ 0.8146,  0.0856, -0.9194]],

        [[ 0.5977,  1.6446,  0.6585],
         [ 0.1729, -1.8484, -0.6663],
         [ 1.7829,  0.0987, -0.3719],
         [-0.6430,  0.8605, -0.0879]]])
torch.float32
torch.Size([4, 4, 3])


In [41]:
#other functions:
x_ones_like = torch.ones_like(x_tensor) #acquisice tutte le proprietà del tensore che gli passo come parametro, ma tutti 1
print(x_ones_like)
print(x_ones_like.shape)
print(x_ones_like.dtype)
#copia tutte le caratteristiche tranne i numeri che lo compongono 

'''
Quindi uun tensore è un oggetto della classe Tensor, e come tale ha degli attributi come: data , shape 
dtype, device(dove si trova il tensore in memoria), requires_grad (questo è un bool), grad (gradiente calcolato per questo tensore),
grad_fn, grad_fn.grad_fn, is_leaf, is_meta, layout,
'''

x_rand_like = torch.rand_like(x_tensor , dtype=torch.float) #attenzione se non specifico quel datatype mi da un errore. perchè è int32
print(x_rand_like)
print(x_rand_like.shape)    
print(x_rand_like.dtype)    




tensor([[1, 1],
        [1, 1],
        [1, 1]])
torch.Size([3, 2])
torch.int64
tensor([[0.2062, 0.4490],
        [0.3901, 0.9241],
        [0.0563, 0.8859]])
torch.Size([3, 2])
torch.float32


ATTENNZIONE: IN GENERALE è MOLTO UTILE STAMPARE MOLTE VOLTE LE SHAPE DEI TENSORI DURANTE I CALCOLI NELLA PARTE DI FORWARD DELLE RETI. PERCHE SONO UN OTTIMO INDICE PER CAPIRE SE CI SONO ERRORI NEL CODICE O SE SONO PRESENTI DELLE INCOMPATIBILITA'. ATTENZIONE 

Indexing e slicing

In [42]:
def spazio():
    print("\n")
    print("------------------------------------")
    print("\n")

x_rand = torch.rand(3, 4 ,4 ) #nota che il primo numero sono in canali.
print(x_rand.shape)    
print(x_rand)
spazio()
print(x_rand[0,1])
spazio()
print(x_rand[0,0,0])
spazio()
print(x_rand[2,0])
spazio()
# se voglio printare la colonna 0 di un i canale
print(x_rand[0,:,0])
spazio()
# se voglio printare la colonna 0 di tutti i canali
print(x_rand[:,:,0])
spazio()

torch.Size([3, 4, 4])
tensor([[[0.3647, 0.7906, 0.8069, 0.5739],
         [0.4538, 0.4711, 0.4282, 0.1698],
         [0.1394, 0.2403, 0.9846, 0.7111],
         [0.4413, 0.0818, 0.8512, 0.6551]],

        [[0.7172, 0.0095, 0.6161, 0.0510],
         [0.4092, 0.1244, 0.5164, 0.9116],
         [0.1470, 0.4788, 0.5393, 0.8873],
         [0.6519, 0.3641, 0.4095, 0.9264]],

        [[0.3628, 0.3112, 0.1685, 0.7596],
         [0.8758, 0.6628, 0.4631, 0.2088],
         [0.4245, 0.2770, 0.8875, 0.6682],
         [0.7863, 0.8392, 0.1535, 0.2235]]])


------------------------------------


tensor([0.4538, 0.4711, 0.4282, 0.1698])


------------------------------------


tensor(0.3647)


------------------------------------


tensor([0.3628, 0.3112, 0.1685, 0.7596])


------------------------------------


tensor([0.3647, 0.4538, 0.1394, 0.4413])


------------------------------------


tensor([[0.3647, 0.4538, 0.1394, 0.4413],
        [0.7172, 0.4092, 0.1470, 0.6519],
        [0.3628, 0.8758, 0.42

In [43]:
#i tensori sono mutabili:
A = torch.randn(size =  (3, 3, 3) , dtype= torch.float32)
print(A)
spazio()
A[:,0,0] = 10 #Cambia io primo elemento della prima riga ti tutti i canali
print(A)

tensor([[[ 1.7958,  0.1612,  0.2915],
         [ 0.1919, -0.2951, -1.2383],
         [ 0.3943, -0.9321, -0.7311]],

        [[ 0.2950, -0.7205,  0.9740],
         [-0.2859,  0.7601,  1.1795],
         [-2.2405, -0.0215, -1.1543]],

        [[-0.6118,  0.3665,  0.3854],
         [-0.4565,  0.8864,  0.7573],
         [ 0.6826,  0.2722, -1.1437]]])


------------------------------------


tensor([[[10.0000,  0.1612,  0.2915],
         [ 0.1919, -0.2951, -1.2383],
         [ 0.3943, -0.9321, -0.7311]],

        [[10.0000, -0.7205,  0.9740],
         [-0.2859,  0.7601,  1.1795],
         [-2.2405, -0.0215, -1.1543]],

        [[10.0000,  0.3665,  0.3854],
         [-0.4565,  0.8864,  0.7573],
         [ 0.6826,  0.2722, -1.1437]]])


In [44]:
B_ones  = torch.ones(size=(2,2) , dtype=torch.float32)
#funzione cat, che concatena il tensore:
print(B_ones)
spazio()
t1 = torch.cat(tensors=(B_ones,B_ones), dim=0)
print(t1)
spazio()
t2 = torch.cat(tensors=(B_ones,B_ones), dim=1)
print(t2)
spazio()

tensor([[1., 1.],
        [1., 1.]])


------------------------------------


tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


------------------------------------


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


------------------------------------




In [45]:
#cosa succede se il tensore è piu complicato?
B2_ones = torch.ones(size=(3,3 , 3) , dtype=torch.float32)
print(B2_ones)
spazio()
t4 = torch.cat([B2_ones, B2_ones], dim=0)
print(t4)
spazio()
'''t5 = torch.cat(tensor = [B2_ones, B2_ones], dim=1)
print(t5)
spazio()'''

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------




't5 = torch.cat(tensor = [B2_ones, B2_ones], dim=1)\nprint(t5)\nspazio()'

Operazioni tra tensori:

In [46]:
#moltiplicazione matriciale:
print(B_ones)
spazio()
y1 = torch.matmul(B_ones , B_ones)
print(y1)
spazio()
#complichiamo
y2= torch.matmul(B2_ones, B2_ones) #eh devi capire come funzionano i moltiplicatori tra matrici
print(y2)   
spazio()
c = torch.ones(size=(3,2,2) , dtype=torch.float32)
print(c)    
spazio()
y3= torch.matmul(c , c)
print(y3)
spazio()
y3= c.matmul(c)
print(y3)
spazio()
y3= c @ c
print(y3)
spazio()


tensor([[1., 1.],
        [1., 1.]])


------------------------------------


tensor([[2., 2.],
        [2., 2.]])


------------------------------------


tensor([[[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]]])


------------------------------------


tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


------------------------------------


tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])


------------------------------------


tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])


------------------------------------


tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
        

Element wise

In [47]:
print(B2_ones)
spazio()
z1 = torch.mul(B2_ones , B2_ones)
print(z1)
spazio()
z1= B2_ones.mul(B2_ones)
print(z1)
spazio()
z1= B2_ones * B2_ones
print(z1)   
spazio()

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


-----------------------

Operazioni di statistiche:

In [48]:
print(z1)
spazio()

sum = z1.sum()
print(sum)
print(sum.shape)
print(type(sum))
spazio()

#come faccio a trasformarlo in uno scalare?
sum = sum.item() #estrae l'elemento del tensore
print(sum)
print(type(sum))
spazio()



tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor(27.)
torch.Size([])
<class 'torch.Tensor'>


------------------------------------


27.0
<class 'float'>


------------------------------------




Operazione inplace:

In [49]:
print(z1)
spazio()
print(z1.add_(5))
spazio()
print(z1+5)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]]])


------------------------------------


tensor([[[11., 11., 11.],
         [11., 11., 11.],
         [11., 11., 11.]],

        [[11., 11., 11.],
         [11., 11., 11.],
         [11., 11., 11.]],

        [[11., 11., 11.],
         [11., 11., 11.],
         [11., 11., 11.]]])


In [50]:
#Vediamo come passare da tensor a numpy:
b = torch.ones(size=(5,)) #stiamo creando un vettore
print(b)
print(type(b))
print(b.shape)
spazio()

numpy_b = b.numpy()
print(numpy_b)
print(type(numpy_b))
print(numpy_b.shape)
spazio()

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
torch.Size([5])


------------------------------------


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
(5,)


------------------------------------




ATTENZIONE!!!

In [51]:
D = torch.ones(size=(5,) , dtype=torch.float64)
print(D)
spazio()
n_D = D.numpy()
print(n_D)
spazio()

#Attenzione a quello che faccio:
np.add(n_D , 10 , out=n_D) 
print(n_D)
print(D)
spazio()

'''
    Attenzione perchè spostiamo il numpy ma stiamo scambiando il riferimento. L'ggetto D continua ad esistere, e
    la variabile D che codifica un oggetto tensor, punta alla stessa zona di memoria a cui punta n_D.
    Non viene creato un nuovo oggetto numpy. 
    Quindi se modifico i valori nell'array numpy, modifico la stessa zona di memoria di D. Quindi vedo le stesse modifiche.
'''

#questo non accade se non faccio le inplace: questo perchè creo un nuovo oggetto numpy, i cui valori sono presi da un altro oggetto. La zona di memoria è differente.
n_D = n_D + 10
print(n_D)
print(D)
spazio()



tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


------------------------------------


[1. 1. 1. 1. 1.]


------------------------------------


[11. 11. 11. 11. 11.]
tensor([11., 11., 11., 11., 11.], dtype=torch.float64)


------------------------------------


[21. 21. 21. 21. 21.]
tensor([11., 11., 11., 11., 11.], dtype=torch.float64)


------------------------------------


