Let's begin with an introduction to pytorch.

In [3]:
import numpy as np 
import torch


The principal element in pytorch is the tensor.

In [4]:
#that is a list.
data = [
    [1, 2],
    [3, 4],
    [5, 6]
]
print(data)
print(type(data))

#that is a tensor. quando lavoreremo con le immagini lavoreremo con tensori a 4 dimensioni
#Questo perchè l'immagine sarà formata da 3 dimensioni: altezza, larghezza e canali (RGB) più una batch dimensione. lo vedremo in seguito...
x_data = torch.tensor(data) 
print(x_data)
print(type(x_data))



[[1, 2], [3, 4], [5, 6]]
<class 'list'>
tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>


In [5]:
#Posso creare un tensore partendo da un array numpy.
import numpy as np
np_array = np.array(data)
print(np_array)
print(type(np_array))

#and then
#prende in oggetto un numpy array e lo trasforma in un tensore torch.
x_tensor = torch.from_numpy(np_array)
print(x_tensor)
print(type(x_tensor))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>


In [7]:
#alcune funzioni:
x_ones = torch.ones(size=(4,4,3) , dtype=torch.int32) #this is a 4x4 x3 tensor. 
print(x_ones)
print(x_ones.shape)
print(x_ones.dtype)


tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int32)
torch.Size([4, 4, 4])
torch.int32


In [8]:
x_zero = torch.zeros(4, 4, 3)
print(x_zero)
print(x_zero.shape)
print(x_zero.dtype)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([4, 4, 3])
torch.float32


In [10]:
x_rand = torch.randn(size=(4,4,3) , dtype=torch.float32) #questa la posso proprio immaginare come un'immagine.
print(x_rand)   
print(x_rand.dtype)
print(x_rand.shape)

tensor([[[-0.3847,  0.8227,  0.0955],
         [-1.7113,  0.8670,  0.0088],
         [-1.3341, -0.7041,  0.9964],
         [ 0.3780,  1.1648, -1.5300]],

        [[-0.3494, -0.1215, -0.2999],
         [-1.1565, -0.1424, -2.0532],
         [ 1.2090, -0.5904, -1.3280],
         [ 0.6573, -1.2722, -1.1755]],

        [[-3.1750,  0.5361,  0.8438],
         [-0.2098,  0.7864,  1.5080],
         [ 0.2584,  0.1044, -0.9781],
         [ 0.4068,  1.2692,  0.3516]],

        [[-0.9595, -1.3258, -1.1852],
         [ 0.4922,  0.6220, -0.3408],
         [ 0.6443,  1.1071, -0.2279],
         [-2.0533, -1.0610,  0.5774]]])
torch.float32
torch.Size([4, 4, 3])


In [16]:
#other functions:
x_ones_like = torch.ones_like(x_tensor) #acquisice tutte le proprietà del tensore che gli passo come parametro, ma tutti 1
print(x_ones_like)
print(x_ones_like.shape)
print(x_ones_like.dtype)
#copia tutte le caratteristiche tranne i numeri che lo compongono 

'''
Quindi uun tensore è un oggetto della classe Tensor, e come tale ha degli attributi come: data , shape 
dtype, device(dove si trova il tensore in memoria), requires_grad (questo è un bool), grad (gradiente calcolato per questo tensore),
grad_fn, grad_fn.grad_fn, is_leaf, is_meta, layout,
'''

x_rand_like = torch.rand_like(x_tensor , dtype=torch.float) #attenzione se non specifico quel datatype mi da un errore. perchè è int32
print(x_rand_like)
print(x_rand_like.shape)    
print(x_rand_like.dtype)    




tensor([[1, 1],
        [1, 1],
        [1, 1]])
torch.Size([3, 2])
torch.int64
tensor([[0.4550, 0.4586],
        [0.5122, 0.0381],
        [0.8464, 0.5293]])
torch.Size([3, 2])
torch.float32


ATTENNZIONE: IN GENERALE è MOLTO UTILE STAMPARE MOLTE VOLTE LE SHAPE DEI TENSORI DURANTE I CALCOLI NELLA PARTE DI FORWARD DELLE RETI. PERCHE SONO UN OTTIMO INDICE PER CAPIRE SE CI SONO ERRORI NEL CODICE O SE SONO PRESENTI DELLE INCOMPATIBILITA'. ATTENZIONE 

Indexing e slicing

In [34]:
def spazio():
    print("\n")
    print("------------------------------------")
    print("\n")

x_rand = torch.rand(3, 4 ,4 ) #nota che il primo numero sono in canali.
print(x_rand.shape)    
print(x_rand)
spazio()
print(x_rand[0,1])
spazio()
print(x_rand[0,0,0])
spazio()
print(x_rand[2,0])
spazio()
# se voglio printare la colonna 0 di un i canale
print(x_rand[0,:,0])
spazio()
# se voglio printare la colonna 0 di tutti i canali
print(x_rand[:,:,0])
spazio()

torch.Size([3, 4, 4])
tensor([[[0.2079, 0.4988, 0.4595, 0.5666],
         [0.5893, 0.3465, 0.0337, 0.4309],
         [0.7727, 0.6326, 0.8382, 0.9984],
         [0.1371, 0.2624, 0.6468, 0.3218]],

        [[0.9985, 0.4005, 0.3535, 0.5075],
         [0.2741, 0.1165, 0.8090, 0.5368],
         [0.9187, 0.4605, 0.5234, 0.3540],
         [0.4450, 0.1810, 0.7851, 0.6035]],

        [[0.9950, 0.4548, 0.8796, 0.8965],
         [0.0193, 0.2775, 0.6440, 0.9986],
         [0.0744, 0.5807, 0.1537, 0.1849],
         [0.8800, 0.9864, 0.7592, 0.5137]]])


------------------------------------


tensor([0.5893, 0.3465, 0.0337, 0.4309])


------------------------------------


tensor(0.2079)


------------------------------------


tensor([0.9950, 0.4548, 0.8796, 0.8965])


------------------------------------


tensor([0.2079, 0.5893, 0.7727, 0.1371])


------------------------------------


tensor([[0.2079, 0.5893, 0.7727, 0.1371],
        [0.9985, 0.2741, 0.9187, 0.4450],
        [0.9950, 0.0193, 0.07

In [36]:
#i tensori sono mutabili:
A = torch.randn(size =  (3, 3, 3) , dtype= torch.float32)
print(A)
spazio()
A[:,0,0] = 10 #Cambia io primo elemento della prima riga ti tutti i canali
print(A)

tensor([[[ 0.3998,  0.0982, -1.8311],
         [-1.8990, -0.2237, -0.7999],
         [-2.7796, -0.2907,  0.2577]],

        [[ 0.5038, -2.0219, -0.4609],
         [ 1.3271,  0.6482,  0.1041],
         [-1.3979, -1.2751,  0.3400]],

        [[ 1.4176,  1.8996, -0.2430],
         [ 1.3704, -0.2269, -0.8369],
         [ 0.0286, -1.2299, -1.0448]]])


------------------------------------


tensor([[[10.0000,  0.0982, -1.8311],
         [-1.8990, -0.2237, -0.7999],
         [-2.7796, -0.2907,  0.2577]],

        [[10.0000, -2.0219, -0.4609],
         [ 1.3271,  0.6482,  0.1041],
         [-1.3979, -1.2751,  0.3400]],

        [[10.0000,  1.8996, -0.2430],
         [ 1.3704, -0.2269, -0.8369],
         [ 0.0286, -1.2299, -1.0448]]])


In [37]:
B_ones  = torch.ones(size=(2,2) , dtype=torch.float32)
#funzione cat, che concatena il tensore:
print(B_ones)
spazio()
t1 = torch.cat(tensors=(B_ones,B_ones), dim=0)
print(t1)
spazio()
t2 = torch.cat(tensors=(B_ones,B_ones), dim=1)
print(t2)
spazio()

tensor([[1., 1.],
        [1., 1.]])


------------------------------------


tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


------------------------------------


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


------------------------------------




In [43]:
#cosa succede se il tensore è piu complicato?
B2_ones = torch.ones(size=(3,3 , 3) , dtype=torch.float32)
print(B2_ones)
spazio()
t4 = torch.cat([B2_ones, B2_ones], dim=0)
print(t4)
spazio()
'''t5 = torch.cat(tensor = [B2_ones, B2_ones], dim=1)
print(t5)
spazio()'''

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------




't5 = torch.cat(tensor = [B2_ones, B2_ones], dim=1)\nprint(t5)\nspazio()'