Let's begin with an introduction to pytorch.

In [30]:
import numpy as np 
import torch


The principal element in pytorch is the tensor.

In [31]:
#that is a list.
data = [
    [1, 2],
    [3, 4],
    [5, 6]
]
print(data)
print(type(data))

#that is a tensor. quando lavoreremo con le immagini lavoreremo con tensori a 4 dimensioni
#Questo perchè l'immagine sarà formata da 3 dimensioni: altezza, larghezza e canali (RGB) più una batch dimensione. lo vedremo in seguito...
x_data = torch.tensor(data) 
print(x_data)
print(type(x_data))



[[1, 2], [3, 4], [5, 6]]
<class 'list'>
tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>


In [32]:
#Posso creare un tensore partendo da un array numpy.
import numpy as np
np_array = np.array(data)
print(np_array)
print(type(np_array))

#and then
#prende in oggetto un numpy array e lo trasforma in un tensore torch.
x_tensor = torch.from_numpy(np_array)
print(x_tensor)
print(type(x_tensor))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>


In [33]:
#alcune funzioni:
x_ones = torch.ones(size=(4,4,3) , dtype=torch.int32) #this is a 4x4 x3 tensor. 
print(x_ones)
print(x_ones.shape)
print(x_ones.dtype)


tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)
torch.Size([4, 4, 3])
torch.int32


In [34]:
x_zero = torch.zeros(4, 4, 3)
print(x_zero)
print(x_zero.shape)
print(x_zero.dtype)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([4, 4, 3])
torch.float32


In [35]:
x_rand = torch.randn(size=(4,4,3) , dtype=torch.float32) #questa la posso proprio immaginare come un'immagine.
print(x_rand)   
print(x_rand.dtype)
print(x_rand.shape)

tensor([[[ 0.2984,  1.1838,  0.2283],
         [ 1.2124, -0.2089, -0.3709],
         [ 1.2870,  0.7129,  0.1439],
         [ 0.7034, -1.0548, -0.0424]],

        [[-0.4249,  0.4306,  0.2025],
         [ 1.7144,  0.9361, -0.8138],
         [ 1.8745,  1.6072,  0.9773],
         [-1.7325,  1.6324,  0.1219]],

        [[ 1.8066,  0.3208,  0.3949],
         [-0.6777,  0.1000,  0.0858],
         [-1.1362,  0.6061,  2.1683],
         [-0.7197,  0.4004, -1.6031]],

        [[-3.2223, -1.6236,  1.3183],
         [-0.2496,  0.4313, -1.5395],
         [-1.5285, -0.3611,  0.4311],
         [ 2.0498,  1.2325, -0.5751]]])
torch.float32
torch.Size([4, 4, 3])


In [36]:
#other functions:
x_ones_like = torch.ones_like(x_tensor) #acquisice tutte le proprietà del tensore che gli passo come parametro, ma tutti 1
print(x_ones_like)
print(x_ones_like.shape)
print(x_ones_like.dtype)
#copia tutte le caratteristiche tranne i numeri che lo compongono 

'''
Quindi uun tensore è un oggetto della classe Tensor, e come tale ha degli attributi come: data , shape 
dtype, device(dove si trova il tensore in memoria), requires_grad (questo è un bool), grad (gradiente calcolato per questo tensore),
grad_fn, grad_fn.grad_fn, is_leaf, is_meta, layout,
'''

x_rand_like = torch.rand_like(x_tensor , dtype=torch.float) #attenzione se non specifico quel datatype mi da un errore. perchè è int32
print(x_rand_like)
print(x_rand_like.shape)    
print(x_rand_like.dtype)    




tensor([[1, 1],
        [1, 1],
        [1, 1]])
torch.Size([3, 2])
torch.int64
tensor([[0.0043, 0.9567],
        [0.5263, 0.8463],
        [0.9479, 0.3230]])
torch.Size([3, 2])
torch.float32


ATTENNZIONE: IN GENERALE è MOLTO UTILE STAMPARE MOLTE VOLTE LE SHAPE DEI TENSORI DURANTE I CALCOLI NELLA PARTE DI FORWARD DELLE RETI. PERCHE SONO UN OTTIMO INDICE PER CAPIRE SE CI SONO ERRORI NEL CODICE O SE SONO PRESENTI DELLE INCOMPATIBILITA'. ATTENZIONE 

Indexing e slicing

In [37]:
def spazio():
    print("\n")
    print("------------------------------------")
    print("\n")

x_rand = torch.rand(3, 4 ,4 ) #nota che il primo numero sono in canali.
print(x_rand.shape)    
print(x_rand)
spazio()
print(x_rand[0,1])
spazio()
print(x_rand[0,0,0])
spazio()
print(x_rand[2,0])
spazio()
# se voglio printare la colonna 0 di un i canale
print(x_rand[0,:,0])
spazio()
# se voglio printare la colonna 0 di tutti i canali
print(x_rand[:,:,0])
spazio()

torch.Size([3, 4, 4])
tensor([[[0.8692, 0.7329, 0.4339, 0.0303],
         [0.3268, 0.1557, 0.2936, 0.4398],
         [0.9666, 0.8604, 0.8875, 0.0063],
         [0.3809, 0.3918, 0.6764, 0.8056]],

        [[0.0577, 0.0219, 0.4848, 0.3622],
         [0.9070, 0.6077, 0.7758, 0.1249],
         [0.8641, 0.7096, 0.9258, 0.4566],
         [0.6141, 0.1079, 0.1756, 0.8742]],

        [[0.1642, 0.1167, 0.3685, 0.8056],
         [0.3677, 0.1127, 0.5335, 0.0623],
         [0.9177, 0.5055, 0.9541, 0.7998],
         [0.8997, 0.7619, 0.5844, 0.8720]]])


------------------------------------


tensor([0.3268, 0.1557, 0.2936, 0.4398])


------------------------------------


tensor(0.8692)


------------------------------------


tensor([0.1642, 0.1167, 0.3685, 0.8056])


------------------------------------


tensor([0.8692, 0.3268, 0.9666, 0.3809])


------------------------------------


tensor([[0.8692, 0.3268, 0.9666, 0.3809],
        [0.0577, 0.9070, 0.8641, 0.6141],
        [0.1642, 0.3677, 0.91

In [38]:
#i tensori sono mutabili:
A = torch.randn(size =  (3, 3, 3) , dtype= torch.float32)
print(A)
spazio()
A[:,0,0] = 10 #Cambia io primo elemento della prima riga ti tutti i canali
print(A)

tensor([[[ 0.1352,  0.0992,  0.3674],
         [-0.1601, -0.0502,  1.7891],
         [ 0.6074, -1.1142,  0.8660]],

        [[-0.3055, -0.3996,  1.0612],
         [-0.0456, -0.5683,  1.6161],
         [-0.2065,  0.0327,  0.0131]],

        [[-1.0597,  0.5864, -1.7324],
         [ 1.0528, -1.0209, -1.6113],
         [ 0.4512,  0.7679, -0.6754]]])


------------------------------------


tensor([[[10.0000,  0.0992,  0.3674],
         [-0.1601, -0.0502,  1.7891],
         [ 0.6074, -1.1142,  0.8660]],

        [[10.0000, -0.3996,  1.0612],
         [-0.0456, -0.5683,  1.6161],
         [-0.2065,  0.0327,  0.0131]],

        [[10.0000,  0.5864, -1.7324],
         [ 1.0528, -1.0209, -1.6113],
         [ 0.4512,  0.7679, -0.6754]]])


In [39]:
B_ones  = torch.ones(size=(2,2) , dtype=torch.float32)
#funzione cat, che concatena il tensore:
print(B_ones)
spazio()
t1 = torch.cat(tensors=(B_ones,B_ones), dim=0)
print(t1)
spazio()
t2 = torch.cat(tensors=(B_ones,B_ones), dim=1)
print(t2)
spazio()

tensor([[1., 1.],
        [1., 1.]])


------------------------------------


tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


------------------------------------


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


------------------------------------




In [40]:
#cosa succede se il tensore è piu complicato?
B2_ones = torch.ones(size=(3,3 , 3) , dtype=torch.float32)
print(B2_ones)
spazio()
t4 = torch.cat([B2_ones, B2_ones], dim=0)
print(t4)
spazio()
'''t5 = torch.cat(tensor = [B2_ones, B2_ones], dim=1)
print(t5)
spazio()'''

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------




't5 = torch.cat(tensor = [B2_ones, B2_ones], dim=1)\nprint(t5)\nspazio()'

Operazioni tra tensori:

In [42]:
#moltiplicazione matriciale:
print(B_ones)
spazio()
y1 = torch.matmul(B_ones , B_ones)
print(y1)
spazio()
#complichiamo
y2= torch.matmul(B2_ones, B2_ones) #eh devi capire come funzionano i moltiplicatori tra matrici
print(y2)   
spazio()
c = torch.ones(size=(3,2,2) , dtype=torch.float32)
print(c)    
spazio()
y3= torch.matmul(c , c)
print(y3)
spazio()
y3= c.matmul(c)
print(y3)
spazio()
y3= c @ c
print(y3)
spazio()


tensor([[1., 1.],
        [1., 1.]])


------------------------------------


tensor([[2., 2.],
        [2., 2.]])


------------------------------------


tensor([[[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]]])


------------------------------------


tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


------------------------------------


tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])


------------------------------------


tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])


------------------------------------


tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
        

Element wise

In [43]:
print(B2_ones)
spazio()
z1 = torch.mul(B2_ones , B2_ones)
print(z1)
spazio()
z1= B2_ones.mul(B2_ones)
print(z1)
spazio()
z1= B2_ones * B2_ones
print(z1)   
spazio()

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


-----------------------

Operazioni di statistiche:

In [47]:
print(z1)
spazio()

sum = z1.sum()
print(sum)
print(sum.shape)
print(type(sum))
spazio()

#come faccio a trasformarlo in uno scalare?
sum = sum.item() #estrae l'elemento del tensore
print(sum)
print(type(sum))
spazio()



tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor(27.)
torch.Size([])
<class 'torch.Tensor'>


------------------------------------


27.0
<class 'float'>


Operazione inplace:

In [49]:
print(z1)
spazio()
print(z1.add_(5))
spazio()
print(z1+5)

tensor([[[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]]])


------------------------------------


tensor([[[11., 11., 11.],
         [11., 11., 11.],
         [11., 11., 11.]],

        [[11., 11., 11.],
         [11., 11., 11.],
         [11., 11., 11.]],

        [[11., 11., 11.],
         [11., 11., 11.],
         [11., 11., 11.]]])


------------------------------------


tensor([[[16., 16., 16.],
         [16., 16., 16.],
         [16., 16., 16.]],

        [[16., 16., 16.],
         [16., 16., 16.],
         [16., 16., 16.]],

        [[16., 16., 16.],
         [16., 16., 16.],
         [16., 16., 16.]]])


In [50]:
#Vediamo come passare da tensor a numpy:
b = torch.ones(size=(5,)) #stiamo creando un vettore
print(b)
print(type(b))
print(b.shape)
spazio()

numpy_b = b.numpy()
print(numpy_b)
print(type(numpy_b))
print(numpy_b.shape)
spazio()

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
torch.Size([5])


------------------------------------


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
(5,)


------------------------------------




ATTENZIONE!!!

In [55]:
D = torch.ones(size=(5,) , dtype=torch.float64)
print(D)
spazio()
n_D = D.numpy()
print(n_D)
spazio()

#Attenzione a quello che faccio:
np.add(n_D , 10 , out=n_D) 
print(n_D)
print(D)
spazio()

'''
    Attenzione perchè spostiamo il numpy ma stiamo scambiando il riferimento. L'ggetto D continua ad esistere, e
    la variabile D che codifica un oggetto tensor, punta alla stessa zona di memoria a cui punta n_D.
    Non viene creato un nuovo oggetto numpy. 
    Quindi se modifico i valori nell'array numpy, modifico la stessa zona di memoria di D. Quindi vedo le stesse modifiche.
'''

#questo non accade se non faccio le inplace: questo perchè creo un nuovo oggetto numpy, i cui valori sono presi da un altro oggetto. La zona di memoria è differente.
n_D = n_D + 10
print(n_D)
print(D)
spazio()



tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


------------------------------------


[1. 1. 1. 1. 1.]


------------------------------------


[11. 11. 11. 11. 11.]
tensor([11., 11., 11., 11., 11.], dtype=torch.float64)


------------------------------------


[21. 21. 21. 21. 21.]
tensor([11., 11., 11., 11., 11.], dtype=torch.float64)


------------------------------------


