Proviamo a scrivere con i tensori, quello che avviene all'interno dei neuroni: 

In [15]:

import torch 
import numpy as np
from Lezione_08102024 import spazio
x = torch.ones(size = (5 , ))
y = torch.zeros(size = (3 , ))
print(x)
print(y)
spazio()

'''
we have an input x that is a vector of 5 elements.
Also we have an output y that is a vector of 3 elements.
Basically we can imagine, we have one sample with 5 features. We imagine also that the problem is multiclassification
So we have 3 classes.
I think, probabilly, the higer element of y identify the appartenance to the class.
'''

w = torch.randn(size = (5 , 3 ) , requires_grad=True)
w1 = torch.randn(size = (3 , 5 ) , requires_grad=True)
print(w)
print(w.shape)
print(w1)
print(w1.shape) 
spazio()


'''
Piccola spiegazione sulle dimensioni di w e w1, il professore ha detto che la dimensione dovrà essere 
5x3, ma nelle NN dal punto di vista matematico ha senso fare 3x5. Questo perchè nei neuroni
ci sarà il frutto dei risultati del prodotto W.x + b.
'''

b = torch.randn(size = (3 , ) , requires_grad=True) #tre sono i neuroni di output.
print(b)
print(b.shape)
spazio()



tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0.])


------------------------------------


tensor([[ 0.4012, -1.2462, -0.8468],
        [ 0.1535, -1.1417,  0.2827],
        [-0.8094,  0.6223,  1.4280],
        [-1.0686,  0.6513,  0.0415],
        [ 1.1277, -1.3463,  1.0221]], requires_grad=True)
torch.Size([5, 3])
tensor([[-0.2145,  0.4940, -0.1844, -0.4558,  0.6861],
        [-0.1431, -0.6246, -1.8327,  3.0185,  0.6079],
        [-0.8951, -0.7414,  0.0236,  1.0189,  0.6565]], requires_grad=True)
torch.Size([3, 5])


------------------------------------


tensor([ 0.2974, -0.4629,  1.1129], requires_grad=True)
torch.Size([3])


------------------------------------




In [20]:
#Implementiamo la moltimplicazione:
z = torch.matmul(x, w) + b 
print(z)
print(z.shape)
spazio()
z1= torch.matmul(w1, x) + b 
print(z1)
print(z1.shape)
spazio()
'''
Qui divento pazzo, ovviamente queste due cose non sono la stessa cosa!
Anche se la dimensione è la stessa, non sono la stessa cosa!
va bene lo stesso??? Vedremo, io continuerò a implementarli insieme.
'''

tensor([ 0.1018, -2.9235,  3.0404], grad_fn=<AddBackward0>)
torch.Size([3])


------------------------------------


tensor([0.6228, 0.5630, 1.1754], grad_fn=<AddBackward0>)
torch.Size([3])


------------------------------------




'\nQui divento pazzo, ovviamente queste due cose non sono la stessa cosa!\nAnche se la dimensione è la stessa, non sono la stessa cosa!\nva bene lo stesso??? Vedremo, io continuerò a implementarli insieme.\n'

In [23]:
#Calcolo della Loss: 
loss = torch.nn.functional.binary_cross_entropy_with_logits(z , y)
print(loss)
spazio()
loss1 = torch.nn.functional.binary_cross_entropy_with_logits(z1 , y)
print(loss1)
spazio()


tensor(1.2949, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


------------------------------------


tensor(1.1701, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


------------------------------------




A questo punto una volta che abbiamo la nostra loss function, quello che si fa è propagare il gradiente per aggiornare i parametri. Possiamo avere un piccolo aiutino per effettuare questa backpropagation.

In [24]:
#pytorch pensa all'implementazione della backpropagation.
#Noi implementiamo solo il forward.

print("gradient function di z:" , z.grad_fn )
spazio()
print("gradient function di z1:" , z1.grad_fn )
spazio()

'''
Eseguendo lui ci dice che la funzione che ha generato z è una addbackward cioè una somma, poichè z di fatto è una somma tra matmul e il vettore b
A sua volta lui dirà che torch.matmul è una variabile che è generato come moltiplicazione tra matrici x e w. 
Poi va su x e w, che sono la radice dell'albero di computazione e mi fermo.
'''

gradient function di z: <AddBackward0 object at 0x7f7cb920bc10>


------------------------------------


gradient function di z1: <AddBackward0 object at 0x7f7cb920bc10>


------------------------------------




"\nEseguendo lui ci dice che la funzione che ha generato z è una addbackward cioè una somma, poichè z di fatto è una somma tra matmul e il vettore b\nA sua volta lui dirà che torch.matmul è una variabile che è generato come moltiplicazione tra matrici x e w. \nPoi va su x e w, che sono la radice dell'albero di computazione e mi fermo.\n"

In [25]:
#Con la funzione Backword che viene iinvocata sulla loss, allora viene propagato il gradiente e viene applicato.
loss.backward()
spazio()
loss1.backward()
spazio()

'''
Quello che succede è che viene effettuata una propagazione all'indietro di tutto il gradiente, fino alla radice della catena di computazione,
E salva i gradienti, sull'attributo grad di ogni tensore (solo sui tensori in cui ho imposto requires_grad=True).
'''

print(w.grad)
spazio()
print(b.grad)
spazio()
print(w1.grad)
spazio()


#ATTENZIONE: questo è il gradiente per ogni w_i. NON ABBIAMO ANCORA AGGIORNATO I PESI
#Aggiornare i parametri è il compito di un ottimizzatore SGD, ADAM, ecc.



------------------------------------




------------------------------------


tensor([[0.1751, 0.0170, 0.3181],
        [0.1751, 0.0170, 0.3181],
        [0.1751, 0.0170, 0.3181],
        [0.1751, 0.0170, 0.3181],
        [0.1751, 0.0170, 0.3181]])


------------------------------------


tensor([0.3921, 0.2294, 0.5728])


------------------------------------


tensor([[0.2169, 0.2169, 0.2169, 0.2169, 0.2169],
        [0.2124, 0.2124, 0.2124, 0.2124, 0.2124],
        [0.2547, 0.2547, 0.2547, 0.2547, 0.2547]])


------------------------------------


