INTRODUZIONE AL FRAMEWORK PYTORCH:
- UNA SORTA DI GEMELLO DI NUMPY, RIVISITA DELLE FUNZIONE DI NUMPY SUGLI ARRAY.

In [15]:
def spazio():
    print("\n##########################################\n")

In [16]:
import torch
import numpy as np

#Oggetto fondamentale in torch, è il tensore:
#lo creiamo da una lista di liste
data = [
    [1,2],
    [3,4],
    [5,6]
]

print(data)
print(type(data))

spazio()

#Questo è un tensore: di default noi utilizzeremo tendori di 4 dimensioni, ci sarà la batch dell'immagine
x_data = torch.tensor(data = data)
print(x_data)
print(type(x_data))




[[1, 2], [3, 4], [5, 6]]
<class 'list'>

##########################################

tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>


In [17]:
#Creazione tensori da numpy array:
np_array = np.array(data)
print(np_array)
print(type(np_array))

spazio()

x_data = torch.tensor(np_array)
print(x_data)
print(type(x_data))
print(x_data.shape)

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>

##########################################

tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>
torch.Size([3, 2])


In [18]:
#Creaziome tensore con la funzione torch.from_numpy
x_tensor = torch.from_numpy(np_array)
print(x_tensor)
print(type(x_tensor))
print(x_tensor.shape)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>
torch.Size([3, 2])


In [20]:
#Tensori di 1:
x_ones = torch.ones(size=(4,4) , dtype=torch.int32)
print(x_ones)
print(x_ones.dtype)
print(x_ones.shape)

spazio

x_ones2 = torch.ones(size=(3,3,3) , dtype=torch.int32)
print(x_ones2)
print(x_ones2.dtype)
print(x_ones2.shape)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
torch.int32
torch.Size([4, 4])
tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)
torch.int32
torch.Size([3, 3, 3])


In [22]:
#Tensori random: 
x_rand = torch.randn(size=(4,4) , dtype=torch.float32)
print(x_rand)
print(x_rand.dtype)
print(x_rand.shape)

spazio()

#Tensori di zeri: 
zeros =  torch.zeros(size=(4,4), dtype=torch.int32)
print(zeros)
print(zeros.dtype)
print(zeros.shape)

#Oneslike:

x_ones_like = torch.ones_like(input=x_ones2, dtype=torch.float32)
print(x_ones_like)
print(x_ones_like.dtype)
print(x_ones_like.shape)

tensor([[ 1.6754, -0.6493,  1.0817, -1.4089],
        [ 1.7760, -0.6747, -1.0216,  1.7727],
        [ 1.5382,  0.0338, -0.7468, -1.9315],
        [ 0.2760, -0.0499, -0.9218,  1.3848]])
torch.float32
torch.Size([4, 4])

##########################################

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)
torch.int32
torch.Size([4, 4])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.float32
torch.Size([3, 3, 3])


In [25]:
if torch.cuda.is_available():
    x_ones_like = x_ones_like.cuda()
    print(x_ones_like.device)
else :
    print(x_ones_like.device)
    x_ones_like = x_ones_like.cpu()
    print(x_ones_like.device)

cpu
cpu


In [36]:
#Indexind and slicing: 
x_rand = torch.rand_like(x_ones2, dtype=torch.float)
print(x_rand)

spazio()
#Primo elemento della prima demensione:
print(x_rand[0,0,0])
#Primo elemento della seconda dimensione:
print(x_rand[1,0,0])
spazio()

#Blocco la colonna n 2 e prendo tutte le dimensioni e tutte le righe:
print(x_rand[:,:,1])


tensor([[[0.1745, 0.9321, 0.0233],
         [0.6331, 0.1800, 0.7059],
         [0.6943, 0.2384, 0.8077]],

        [[0.9085, 0.2783, 0.0819],
         [0.9024, 0.1028, 0.3394],
         [0.5967, 0.0348, 0.1652]],

        [[0.8164, 0.4484, 0.8003],
         [0.1079, 0.9399, 0.2130],
         [0.1792, 0.6149, 0.1587]]])

##########################################

tensor(0.1745)
tensor(0.9085)

##########################################

tensor([[0.9321, 0.1800, 0.2384],
        [0.2783, 0.1028, 0.0348],
        [0.4484, 0.9399, 0.6149]])


In [37]:
#I tensori sono mutabili quoindi posso cambiare il valore di un elemento:
x_rand[0,0,0] = 100
print(x_rand)

tensor([[[1.0000e+02, 9.3211e-01, 2.3270e-02],
         [6.3310e-01, 1.7995e-01, 7.0588e-01],
         [6.9427e-01, 2.3837e-01, 8.0768e-01]],

        [[9.0850e-01, 2.7834e-01, 8.1863e-02],
         [9.0237e-01, 1.0283e-01, 3.3936e-01],
         [5.9666e-01, 3.4838e-02, 1.6518e-01]],

        [[8.1639e-01, 4.4844e-01, 8.0028e-01],
         [1.0786e-01, 9.3987e-01, 2.1299e-01],
         [1.7920e-01, 6.1494e-01, 1.5866e-01]]])


In [44]:
#funzione cat: concatena i tensori.
A = torch.ones(3, 3)
print(A)
t1 = torch.cat( [A,A,A] , dim=0)
t2 = torch.cat( [A,A,A] , dim=1)
spazio()
print(t1)
spazio()
print(t2)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

##########################################

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

##########################################

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [48]:
A = torch.randn(size=(3,3))
B = torch.randn(size=(3,3))
print(A)
print(A.shape)
spazio()
print(B)
spazio()

t1 = torch.cat([A,B], dim=0)
t2  = torch.cat([A,B], dim=1)
print(t1)
print(t1.shape)
spazio()
print(t2)
print(t2.shape)

tensor([[ 2.2736,  0.9940, -0.7914],
        [-1.0285, -1.7707,  0.5024],
        [ 0.1906, -0.5817,  0.8688]])
torch.Size([3, 3])

##########################################

tensor([[ 0.4506, -2.0344,  0.0886],
        [ 1.1788,  1.1507, -0.3237],
        [-0.2023, -0.4765, -1.8288]])

##########################################

tensor([[ 2.2736,  0.9940, -0.7914],
        [-1.0285, -1.7707,  0.5024],
        [ 0.1906, -0.5817,  0.8688],
        [ 0.4506, -2.0344,  0.0886],
        [ 1.1788,  1.1507, -0.3237],
        [-0.2023, -0.4765, -1.8288]])
torch.Size([6, 3])

##########################################

tensor([[ 2.2736,  0.9940, -0.7914,  0.4506, -2.0344,  0.0886],
        [-1.0285, -1.7707,  0.5024,  1.1788,  1.1507, -0.3237],
        [ 0.1906, -0.5817,  0.8688, -0.2023, -0.4765, -1.8288]])
torch.Size([3, 6])


In [51]:
A = torch.randn(size=(3,3,3))
B = torch.randn(size=(3,3,3))
print(A)
print(A.shape)
spazio()
print(B)
spazio()

t1 = torch.cat([A,B], dim=0)
t2  = torch.cat([A,B], dim=1)
t3 = torch.cat([A,B], dim=2)
print(t1)
print(t1.shape)
spazio()
print(t2)
print(t2.shape)
spazio()
print(t3)
print(t3.shape)

tensor([[[-1.5725,  1.3973,  0.5062],
         [-0.8256, -1.2974,  0.4159],
         [ 0.8145,  0.1356,  1.9208]],

        [[-0.1193, -0.7181,  0.4872],
         [ 0.1750,  0.0176,  0.5566],
         [ 0.2682,  0.3185, -1.3726]],

        [[ 0.0608,  1.3380, -0.4540],
         [ 0.8952, -0.4804,  0.2630],
         [ 1.2929,  1.0277,  0.2392]]])
torch.Size([3, 3, 3])

##########################################

tensor([[[-1.2764, -0.3280, -0.3963],
         [-1.0133,  0.9757,  0.7396],
         [ 1.2744,  0.1244, -1.4560]],

        [[ 0.6494,  0.4028, -0.1259],
         [-2.1674,  1.7520,  0.3530],
         [-1.1716, -0.8745,  0.8088]],

        [[ 0.6587, -0.0279, -0.8335],
         [-0.6393, -1.8341,  0.9919],
         [-1.1604, -0.5687,  2.1948]]])

##########################################

tensor([[[-1.5725,  1.3973,  0.5062],
         [-0.8256, -1.2974,  0.4159],
         [ 0.8145,  0.1356,  1.9208]],

        [[-0.1193, -0.7181,  0.4872],
         [ 0.1750,  0.0176,  0.5566],


In [60]:
#operazioni tensoriali:
B_ones = torch.ones(2,2)
print(B_ones)
spazio()

y1 = torch.matmul(B_ones, B_ones)
print(y1)
spazio()
y1 = B_ones.matmul(B_ones)
print(y1)
spazio()
y1 = B_ones @ B_ones
print(y1)
spazio()
y1 = B_ones.mul(B_ones)
print(y1)
spazio()

#ELEMENT-WISE OPERATIONS:
y2 = B_ones*B_ones
print(y2)

tensor([[1., 1.],
        [1., 1.]])

##########################################

tensor([[2., 2.],
        [2., 2.]])

##########################################

tensor([[2., 2.],
        [2., 2.]])

##########################################

tensor([[2., 2.],
        [2., 2.]])

##########################################

tensor([[1., 1.],
        [1., 1.]])

##########################################

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
C_ones = torch.ones(2,3)
'''k = C_ones.matmul(B_ones)''' #QUESTO DA ERRORE
K = C_ones.T.matmul(B_ones) 
print(K)

'''K = C_ones.T*B_ones'''


#Facciamo due somme:
K_sum  = K.sum()
print(K_sum)
print(K_sum.item()) #prende il valore numerico.

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor(12.)
12.0


In [77]:
#Tensor --> numpy:
D = torch.ones(size = (3,3))
E = torch.ones(size =(5,))
F = torch.ones(size = (3,3,3))
print(D)
spazio()
print(E)
spazio()    
print(F)
spazio()

n_D = D.numpy()
n_E = E.numpy()
n_F = F.numpy()

print(n_D)
spazio()
print(n_E)
spazio()
print(n_F)
print(type(n_F))




tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

##########################################

tensor([1., 1., 1., 1., 1.])

##########################################

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

##########################################

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

##########################################

[1. 1. 1. 1. 1.]

##########################################

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
<class 'numpy.ndarray'>
