Let's begin with an introduction to pytorch.

In [1]:
import numpy as np 
import torch


The principal element in pytorch is the tensor.

In [2]:
#that is a list.
data = [
    [1, 2],
    [3, 4],
    [5, 6]
]
print(data)
print(type(data))

#that is a tensor. quando lavoreremo con le immagini lavoreremo con tensori a 4 dimensioni
#Questo perchè l'immagine sarà formata da 3 dimensioni: altezza, larghezza e canali (RGB) più una batch dimensione. lo vedremo in seguito...
x_data = torch.tensor(data) 
print(x_data)
print(type(x_data))
print(x_data.shape)



[[1, 2], [3, 4], [5, 6]]
<class 'list'>
tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>
torch.Size([3, 2])


In [3]:
#Posso creare un tensore partendo da un array numpy.
import numpy as np
np_array = np.array(data)
print(np_array)
print(type(np_array))

#and then
#prende in oggetto un numpy array e lo trasforma in un tensore torch.
x_tensor = torch.from_numpy(np_array)
print(x_tensor)
print(type(x_tensor))

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4],
        [5, 6]])
<class 'torch.Tensor'>


In [4]:
#alcune funzioni:
x_ones = torch.ones(size=(4,4,3) , dtype=torch.int32) #this is a 4x4 x3 tensor. 
print(x_ones)
print(x_ones.shape)
print(x_ones.dtype)


tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)
torch.Size([4, 4, 3])
torch.int32


In [5]:
x_zero = torch.zeros(4, 4, 3)
print(x_zero)
print(x_zero.shape)
print(x_zero.dtype)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([4, 4, 3])
torch.float32


In [6]:
x_rand = torch.randn(size=(4,4,3) , dtype=torch.float32) #questa la posso proprio immaginare come un'immagine.
print(x_rand)   
print(x_rand.dtype)
print(x_rand.shape)

tensor([[[ 0.1492, -1.3415,  0.5077],
         [-1.8951, -0.0939, -0.3029],
         [ 1.0419, -1.4849,  0.6962],
         [ 0.2672, -0.1070,  0.2849]],

        [[-0.5135, -1.4079, -2.1044],
         [-0.8236, -1.0141,  1.9276],
         [ 0.9004, -0.2232, -2.7778],
         [-0.7605, -0.6471,  1.9310]],

        [[-0.4180,  0.6019,  0.0217],
         [-0.1317,  0.6425,  0.6710],
         [-0.2670,  0.3205,  0.4351],
         [-1.9265,  0.4264,  0.2141]],

        [[-0.6952,  1.0195,  0.6728],
         [-0.7538, -0.5950,  1.1757],
         [ 1.2886, -1.2791, -1.7174],
         [-0.9619,  0.1945,  0.9006]]])
torch.float32
torch.Size([4, 4, 3])


In [7]:
#other functions:
x_ones_like = torch.ones_like(x_tensor) #acquisice tutte le proprietà del tensore che gli passo come parametro, ma tutti 1
print(x_ones_like)
print(x_ones_like.shape)
print(x_ones_like.dtype)
#copia tutte le caratteristiche tranne i numeri che lo compongono 

'''
Quindi uun tensore è un oggetto della classe Tensor, e come tale ha degli attributi come: data , shape 
dtype, device(dove si trova il tensore in memoria), requires_grad (questo è un bool), grad (gradiente calcolato per questo tensore),
grad_fn, grad_fn.grad_fn, is_leaf, is_meta, layout,
'''

x_rand_like = torch.rand_like(x_tensor , dtype=torch.float) #attenzione se non specifico quel datatype mi da un errore. perchè è int32
print(x_rand_like)
print(x_rand_like.shape)    
print(x_rand_like.dtype)    




tensor([[1, 1],
        [1, 1],
        [1, 1]])
torch.Size([3, 2])
torch.int64
tensor([[0.2384, 0.0132],
        [0.2308, 0.8650],
        [0.8203, 0.4881]])
torch.Size([3, 2])
torch.float32


ATTENNZIONE: IN GENERALE è MOLTO UTILE STAMPARE MOLTE VOLTE LE SHAPE DEI TENSORI DURANTE I CALCOLI NELLA PARTE DI FORWARD DELLE RETI. PERCHE SONO UN OTTIMO INDICE PER CAPIRE SE CI SONO ERRORI NEL CODICE O SE SONO PRESENTI DELLE INCOMPATIBILITA'. ATTENZIONE 

Indexing e slicing

In [8]:
def spazio():
    print("\n")
    print("------------------------------------")
    print("\n")

x_rand = torch.rand(3, 4 ,4 ) #nota che il primo numero sono in canali.
print(x_rand.shape)    
print(x_rand)
spazio()
print(x_rand[0,1])
spazio()
print(x_rand[0,0,0])
spazio()
print(x_rand[2,0])
spazio()
# se voglio printare la colonna 0 di un i canale
print(x_rand[0,:,0])
spazio()
# se voglio printare la colonna 0 di tutti i canali
print(x_rand[:,:,0])
spazio()

torch.Size([3, 4, 4])
tensor([[[0.0931, 0.2885, 0.6243, 0.4795],
         [0.4047, 0.7522, 0.8269, 0.0583],
         [0.9363, 0.0703, 0.0276, 0.9492],
         [0.3822, 0.6922, 0.8661, 0.5728]],

        [[0.3827, 0.1850, 0.0161, 0.4339],
         [0.2739, 0.3836, 0.6696, 0.9054],
         [0.4631, 0.6699, 0.4543, 0.6196],
         [0.7439, 0.4275, 0.6936, 0.0716]],

        [[0.5990, 0.2131, 0.9177, 0.8412],
         [0.4800, 0.1457, 0.6503, 0.6095],
         [0.8422, 0.3206, 0.1560, 0.5669],
         [0.0043, 0.6376, 0.7845, 0.5218]]])


------------------------------------


tensor([0.4047, 0.7522, 0.8269, 0.0583])


------------------------------------


tensor(0.0931)


------------------------------------


tensor([0.5990, 0.2131, 0.9177, 0.8412])


------------------------------------


tensor([0.0931, 0.4047, 0.9363, 0.3822])


------------------------------------


tensor([[0.0931, 0.4047, 0.9363, 0.3822],
        [0.3827, 0.2739, 0.4631, 0.7439],
        [0.5990, 0.4800, 0.84

In [9]:
#i tensori sono mutabili:
A = torch.randn(size =  (3, 3, 3) , dtype= torch.float32)
print(A)
spazio()
A[:,0,0] = 10 #Cambia io primo elemento della prima riga ti tutti i canali
print(A)

tensor([[[ 1.8249, -1.8717, -0.9248],
         [-0.9550,  1.0359, -0.7188],
         [-3.0337, -0.8739,  2.4132]],

        [[ 0.1008, -0.5273,  0.1264],
         [-1.0754,  1.7451,  1.0141],
         [ 1.3606, -0.3268, -1.4474]],

        [[ 0.4182, -0.6699, -0.0685],
         [ 0.4893, -0.5215,  1.5553],
         [-1.0479, -0.4898,  1.3264]]])


------------------------------------


tensor([[[10.0000, -1.8717, -0.9248],
         [-0.9550,  1.0359, -0.7188],
         [-3.0337, -0.8739,  2.4132]],

        [[10.0000, -0.5273,  0.1264],
         [-1.0754,  1.7451,  1.0141],
         [ 1.3606, -0.3268, -1.4474]],

        [[10.0000, -0.6699, -0.0685],
         [ 0.4893, -0.5215,  1.5553],
         [-1.0479, -0.4898,  1.3264]]])


In [10]:
B_ones  = torch.ones(size=(2,2) , dtype=torch.float32)
#funzione cat, che concatena il tensore:
print(B_ones)
spazio()
t1 = torch.cat(tensors=(B_ones,B_ones), dim=0)
print(t1)
spazio()
t2 = torch.cat(tensors=(B_ones,B_ones), dim=1)
print(t2)
spazio()

tensor([[1., 1.],
        [1., 1.]])


------------------------------------


tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


------------------------------------


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


------------------------------------




In [11]:
#cosa succede se il tensore è piu complicato?
B2_ones = torch.ones(size=(3,3 , 3) , dtype=torch.float32)
print(B2_ones)
spazio()
t4 = torch.cat([B2_ones, B2_ones], dim=0)
print(t4)
spazio()
'''t5 = torch.cat(tensor = [B2_ones, B2_ones], dim=1)
print(t5)
spazio()'''

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------




't5 = torch.cat(tensor = [B2_ones, B2_ones], dim=1)\nprint(t5)\nspazio()'

Operazioni tra tensori:

In [12]:
#moltiplicazione matriciale:
print(B_ones)
spazio()
y1 = torch.matmul(B_ones , B_ones)
print(y1)
spazio()
#complichiamo
y2= torch.matmul(B2_ones, B2_ones) #eh devi capire come funzionano i moltiplicatori tra matrici
print(y2)   
spazio()
c = torch.ones(size=(3,2,2) , dtype=torch.float32)
print(c)    
spazio()
y3= torch.matmul(c , c)
print(y3)
spazio()
y3= c.matmul(c)
print(y3)
spazio()
y3= c @ c
print(y3)
spazio()


tensor([[1., 1.],
        [1., 1.]])


------------------------------------


tensor([[2., 2.],
        [2., 2.]])


------------------------------------


tensor([[[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]],

        [[3., 3., 3.],
         [3., 3., 3.],
         [3., 3., 3.]]])


------------------------------------


tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


------------------------------------


tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])


------------------------------------


tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]]])


------------------------------------


tensor([[[2., 2.],
         [2., 2.]],

        [[2., 2.],
         [2., 2.]],

        [[2., 2.],
        

Element wise

In [13]:
print(B2_ones)
spazio()
z1 = torch.mul(B2_ones , B2_ones)
print(z1)
spazio()
z1= B2_ones.mul(B2_ones)
print(z1)
spazio()
z1= B2_ones * B2_ones
print(z1)   
spazio()

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


-----------------------

Operazioni di statistiche:

In [14]:
print(z1)
spazio()

sum = z1.sum()
print(sum)
print(sum.shape)
print(type(sum))
spazio()

#come faccio a trasformarlo in uno scalare?
sum = sum.item() #estrae l'elemento del tensore
print(sum)
print(type(sum))
spazio()



tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor(27.)
torch.Size([])
<class 'torch.Tensor'>


------------------------------------


27.0
<class 'float'>


------------------------------------




Operazione inplace:

In [15]:
print(z1)
spazio()
print(z1.add_(5))
spazio()
print(z1+5)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


------------------------------------


tensor([[[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]],

        [[6., 6., 6.],
         [6., 6., 6.],
         [6., 6., 6.]]])


------------------------------------


tensor([[[11., 11., 11.],
         [11., 11., 11.],
         [11., 11., 11.]],

        [[11., 11., 11.],
         [11., 11., 11.],
         [11., 11., 11.]],

        [[11., 11., 11.],
         [11., 11., 11.],
         [11., 11., 11.]]])


In [16]:
#Vediamo come passare da tensor a numpy:
b = torch.ones(size=(5,)) #stiamo creando un vettore
print(b)
print(type(b))
print(b.shape)
spazio()

numpy_b = b.numpy()
print(numpy_b)
print(type(numpy_b))
print(numpy_b.shape)
spazio()

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
torch.Size([5])


------------------------------------


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
(5,)


------------------------------------




ATTENZIONE!!!

In [17]:
D = torch.ones(size=(5,) , dtype=torch.float64)
print(D)
spazio()
n_D = D.numpy()
print(n_D)
spazio()

#Attenzione a quello che faccio:
np.add(n_D , 10 , out=n_D) 
print(n_D)
print(D)
spazio()

'''
    Attenzione perchè spostiamo il numpy ma stiamo scambiando il riferimento. L'ggetto D continua ad esistere, e
    la variabile D che codifica un oggetto tensor, punta alla stessa zona di memoria a cui punta n_D.
    Non viene creato un nuovo oggetto numpy. 
    Quindi se modifico i valori nell'array numpy, modifico la stessa zona di memoria di D. Quindi vedo le stesse modifiche.
'''

#questo non accade se non faccio le inplace: questo perchè creo un nuovo oggetto numpy, i cui valori sono presi da un altro oggetto. La zona di memoria è differente.
n_D = n_D + 10
print(n_D)
print(D)
spazio()



tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


------------------------------------


[1. 1. 1. 1. 1.]


------------------------------------


[11. 11. 11. 11. 11.]
tensor([11., 11., 11., 11., 11.], dtype=torch.float64)


------------------------------------


[21. 21. 21. 21. 21.]
tensor([11., 11., 11., 11., 11.], dtype=torch.float64)


------------------------------------


